version: "3"
services:
  frontend:
    restart: always
    ports: 
      - 8080:8080
    build:
      dockerfile: Dockerfile
      context: ./frontend
  backend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
