version: "3"
services:
  frontend:
    ports: 
      - 8080:8080
    build:
      dockerfile: Dockerfile
      context: ./frontend
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend