version: "3"
services:
  frontend:
    depends_on: 
      - backend
    restart: always
    ports: 
      - 8080:8080
    build:
      dockerfile: Dockerfile
      context: ./frontend
  backend:
    depends_on: 
      - redis
    environment: 
      - REDIS_DNS=redis
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend
  redis:
    image: "redis"
    expose:
      - 6379
