name: Simple Fortune Cookie
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    matrix:
        go-version: [1.15.x, 1.16.x]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: cd ./frontend go build
      - run: cd ./frontend go run frontend
      - run: cd ./backend go build 
      - run: cd ./backend go run backend 
  #Test: 
  #  runs-on: ubuntu-latest
  #  needs: 