env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
name: Simple Fortune Cookie
on: [push, pull_request]
jobs:
  Build:
    runs-on: ubuntu-latest
    container: golang:bullseye
    steps:
      - uses: actions/checkout@v2
      - name: Build go
        uses: actions/setup-go@v2
      - run: cd ./frontend && go build && go test
      - run: cd ./backend && go build 
      - name: Upload repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Docker-image:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ env.docker_username }}
          password: ${{ env.docker_password }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ env.docker_username }}/fortune_cookie:latest
